version: '3.9'

services:
  app:
    build: ./docker/python
    volumes:
      - .venv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'fastapi'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306

  minio:
    build: ./docker/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=rootroot
      - MINIO_ROOT_PASSWORD=secretsecret
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    volumes:
      - ./docker/minio/data:/data

volumes:
  mysql_data:
